runtime: python311

entrypoint: gunicorn -b :$PORT nutrition_project.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "nutrition_project.settings"
  SECRET_KEY: "hlkvjdsfgzhksdjhkjsdxhkjxcnvkjshfoishfsjkxnc-this-with-a-secure-secret"
  DEBUG: "False"
  DB_HOST: "34.172.xx.xx"
  DB_NAME: "nutritiondb"
  DB_USER: "root"
  DB_PASSWORD: "Nutrition_database.1289"
handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
 
