runtime: python311

entrypoint: gunicorn -b :$PORT nutrition_project.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "nutrition_project.settings"
  DB_HOST: "34.70.202.242"
  DB_NAME: "nutritiondb"
  DB_USER: "django_user"
  DB_PASSWORD: "StrongPassword123!"

handlers:
  - url: /static
    static_dir: staticfiles

  - url: /.*
    script: auto
