# Generated by Django 5.2.4 on 2025-11-13 14:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(blank=True, default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealbox',
            name='week_start',
            field=models.DateField(default=datetime.date(2025, 11, 13)),
        ),
    ]
