# Generated by Django 5.2.4 on 2025-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='checkin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_communication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('payment_error', 'Payment Error'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
