# Generated by Django 5.2.4 on 2025-10-23 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_loginotp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
