# Generated by Django 5.2.4 on 2025-10-04 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_checkin_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories_consumed', models.PositiveIntegerField()),
                ('protein_consumed', models.FloatField(help_text='Protein in grams')),
                ('carbs_consumed', models.FloatField(help_text='Carbs in grams')),
                ('fats_consumed', models.FloatField(help_text='Fats in grams')),
                ('fiber_consumed', models.FloatField(default=0, help_text='Fiber in grams')),
                ('water_intake', models.FloatField(blank=True, help_text='Water intake in liters', null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Entry',
                'verbose_name_plural': 'Nutrition Entries',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
