# Generated by Django 5.2.4 on 2025-10-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
