# Generated by Django 5.2.4 on 2025-10-04 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_checkinform_foodbrand_muscle_plan_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrition',
            options={'ordering': ['title'], 'verbose_name': 'Nutrition Program', 'verbose_name_plural': 'Nutrition Programs'},
        ),
        migrations.AlterUniqueTogether(
            name='nutrition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='calories_per_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical Nutrition'), ('women', 'Women’s Nutrition'), ('child', 'Child & Adolescent Nutrition'), ('corporate', 'Corporate Nutrition'), ('personalized', 'Personalized Diet Plan'), ('fitness', 'Expert Fitness Program')], default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nutrition/'),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='long_description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='title',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='calories_consumed',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='carbs_consumed',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='date',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='fats_consumed',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='fiber_consumed',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='protein_consumed',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='water_intake',
        ),
    ]
