# Generated by Django 5.2.4 on 2025-10-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_inventory_price_inventory_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dietition_assigned',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progress',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
