# Generated by Django 5.2.4 on 2025-10-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_dietition_assigned_userprofile_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
