# Generated by Django 5.2.4 on 2025-10-07 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_file_video_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('meals_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('target_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='nutrition',
            options={},
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='calories_per_day',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='title',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='kind',
            field=models.CharField(choices=[('ingredient', 'Ingredient'), ('recipe', 'Recipe')], default='ingredient', max_length=20),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='meal_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutrition',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
