# Generated by Django 5.2.4 on 2025-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userprofile_gender_alter_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='progress',
            field=models.IntegerField(blank=True, help_text='Progress percentage towards goal', null=True),
        ),
    ]
