# Generated by Django 5.2.4 on 2025-11-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userprofile_progress_mealbox_mealboxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealbox',
            name='meals',
            field=models.ManyToManyField(through='app.MealBoxItem', to='app.meal'),
        ),
    ]
