# Generated by Django 5.2.4 on 2025-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mealplan_lesson_files_lesson_image_lesson_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_files/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='files',
            field=models.ManyToManyField(blank=True, to='app.lessonfile'),
        ),
    ]
